export const CRCTOPICS = [
  {id: 1, topic: 'Am I Different?'},
  {id: 3, topic: 'Are We Passing It On?'},
  {id: 4, topic: 'Are We Victims?'},
  {id: 5, topic: 'Attracting Trouble'},
  {id: 7, topic: 'Being Responsible'},
  {id: 8, topic: 'Changing Things We Can'},
  {id: 9, topic: 'Coming to Grips with Fear'},
  {id: 10, topic: 'Contending with Self-Will'},
  {id: 11, topic: 'Controlling the Imagination'},
  {id: 12, topic: 'Coping with Depression'},
  {id: 13, topic: 'Coping with Social Pressure'},
  {id: 14, topic: 'Dealing with Disagreeable People'},
  {id: 15, topic: 'Dealing with Rejection'},
  {id: 16, topic: 'Dealing with the Past'},
  {id: 17, topic: 'Do Material Things Matter?'},
  {id: 18, topic: 'Do We Deserve Success?'},
  {id: 20, topic: 'Does Alcoholism Have a Physical Origin?'},
  {id: 21, topic: 'Does “Easy Does It” Do It?'},
  {id: 22, topic: 'Does Harm Reduction Work?'},
  {id: 23, topic: 'Emotional Sobriety'},
  {id: 24, topic: 'Erasing the Old Tapes'},
  {id: 25, topic: 'Fearing Change'},
  {id: 28, topic: 'Finding True Independence'},
  {id: 29, topic: 'First Things First: Getting Things in Order'},
  {id: 30, topic: 'Getting Beyond People Pleasing'},
  {id: 31, topic: 'Giving Away to Keep'},
  {id: 32, topic: 'Growth through Action'},
  {id: 33, topic: 'Happy Coincidences'},
  {id: 35, topic: 'How to Deal with Impatience How to Keep the Good Tapes'},
  {id: 36, topic: 'How to Find Happy Sobriety'},
  {id: 37, topic: 'How Should We Carry the Message?'},
  {id: 38, topic: 'Hungry, Angry, Lonely, Tired'},
  {id: 39, topic: 'It’s Your Vision That Matters'},
  {id: 40, topic: 'Justified Resentments'},
  {id: 41, topic: 'Keep It Simple'},
  {id: 42, topic: 'Let It Begin with Me'},
  {id: 43, topic: 'Letting Go of Guilt'},
  {id: 44, topic: 'Letting Go of Problems'},
  {id: 45, topic: 'Life after Cloud Nine'},
  {id: 46, topic: 'Live and Let Live'},
  {id: 47, topic: 'Mental Depression after Sobriety'},
  {id: 48, topic: 'Needing Recovery versus Wanting It'},
  {id: 49, topic: 'Old Resentments Flaring Up'},
  {id: 51, topic: 'Resent Someone'},
  {id: 52, topic: 'Responsibilities in Sobriety'},
  {id: 53, topic: 'Should We Have the Four Absolutes?'},
  {id: 54, topic: 'Surrender to Win'},
  {id: 55, topic: 'Taking the Tenth Step'},
  {id: 57, topic: 'The Fear of Rejection'},
  {id: 58, topic: 'The Importance of Continuing'},
  {id: 59, topic: 'The Need for Self-Honesty'},
  {id: 60, topic: 'Tricky Comparisons'},
  {id: 62, topic: 'Truth and Honesty'},
  {id: 63, topic: 'Walk in Dry Places'},
  {id: 64, topic: 'Wanting Instant Gratification'},
  {id: 65, topic: 'We Cannot Live with Anger'},
  {id: 67, topic: 'What about My Old Friends?'},
  {id: 68, topic: 'What Blocks Acceptance?'},
  {id: 69, topic: 'What Is a Principle?'},
  {id: 71, topic: 'What Is Insanity?'},
  {id: 72, topic: 'What Is Living One Day at a Time?'},
  {id: 73, topic: 'What Is Open-Mindedness?'},
  {id: 75, topic: 'What Is Sincerity?'},
  {id: 76, topic: 'What Is Willingness?'},
  {id: 77, topic: 'What’s Needed for Staying Sober'},
  {id: 78, topic: 'When and Why We Are in the Wrong'},
  {id: 79, topic: 'When Have We Made a Decision?'},
  {id: 81, topic: 'When Pride Gets in My Way'},
  {id: 82, topic: 'When the Worst Things Become the Best'},
  {id: 83, topic: 'Who Is an Alcoholic?'},
  {id: 84, topic: 'Whom Can We Fix?'},
  {id: 85, topic: 'Why and How We Should Practice Forgiveness'},
  {id: 86, topic: 'Why Attitude Matters'},
  {id: 87, topic: 'Why Did We Drink?'},
  {id: 88, topic: 'Why Do I Keep Coming Back?'},
  {id: 89, topic: 'Why Have a Primary Purpose?'},
  {id: 90, topic: 'Why Help Is Needed'},
  {id: 91, topic: 'Why Is One Drink So Bad?'},
  {id: 92, topic: 'Why Keep Coming Back?'},
  {id: 93, topic: 'Why Resentment Leads the Pack'},
  {id: 94, topic: 'Why Should We Make Amends?'},
  {id: 95, topic: 'Why Suffer to Get Well?'},
  {id: 96, topic: 'Why Work the Tenth Step?'},
  {id: 97, topic: 'Willingness Is the Key'},
  {id: 98, topic: 'Winning the Boredom Battle'},
];
