export const CRCTOPICS = [
  {id: 1, body: 'Am I Different?'},
  {id: 2, body: 'Are Alcoholics Perfectionists?'},
  {id: 3, body: 'Are We Passing It On?'},
  {id: 4, body: 'Are We Victims?'},
  {id: 5, body: 'Attracting Trouble'},
  {id: 7, body: 'Being Responsible'},
  {id: 8, body: 'Changing Things We Can'},
  {id: 9, body: 'Coming to Grips with Fear'},
  {id: 10, body: 'Contending with Self-Will'},
  {id: 11, body: 'Controlling the Imagination'},
  {id: 12, body: 'Coping with Depression'},
  {id: 13, body: 'Coping with Social Pressure'},
  {id: 14, body: 'Dealing with Disagreeable People'},
  {id: 15, body: 'Dealing with Rejection'},
  {id: 16, body: 'Dealing with the Past'},
  {id: 17, body: 'Do Material Things Matter?'},
  {id: 18, body: 'Do We Deserve Success?'},
  {id: 20, body: 'Does Alcoholism Have a Physical Origin?'},
  {id: 21, body: 'Does “Easy Does It” Do It?'},
  {id: 22, body: 'Does Harm Reduction Work?'},
  {id: 23, body: 'Emotional Sobriety'},
  {id: 24, body: 'Erasing the Old Tapes'},
  {id: 25, body: 'Fearing Change'},
  {id: 28, body: 'Finding True Independence'},
  {id: 29, body: 'First Things First: Getting Things in Order'},
  {id: 30, body: 'Getting Beyond People Pleasing'},
  {id: 31, body: 'Giving Away to Keep'},
  {id: 32, body: 'Growth through Action'},
  {id: 33, body: 'Happy Coincidences'},
  {id: 35, body: 'How to Deal with Impatience How to Keep the Good Tapes'},
  {id: 36, body: 'How to Find Happy Sobriety'},
  {id: 37, body: 'How Should We Carry the Message?'},
  {id: 38, body: 'Hungry, Angry, Lonely, Tired'},
  {id: 39, body: 'It’s Your Vision That Matters'},
  {id: 40, body: 'Justified Resentments'},
  {id: 41, body: 'Keep It Simple'},
  {id: 42, body: 'Let It Begin with Me'},
  {id: 43, body: 'Letting Go of Guilt'},
  {id: 44, body: 'Letting Go of Problems'},
  {id: 45, body: 'Life after Cloud Nine'},
  {id: 46, body: 'Live and Let Live'},
  {id: 47, body: 'Mental Depression after Sobriety'},
  {id: 48, body: 'Needing Recovery versus Wanting It'},
  {id: 49, body: 'Old Resentments Flaring Up'},
  {id: 51, body: 'Resent Someone'},
  {id: 52, body: 'Responsibilities in Sobriety'},
  {id: 53, body: 'Should We Have the Four Absolutes?'},
  {id: 54, body: 'Surrender to Win'},
  {id: 55, body: 'Taking the Tenth Step'},
  {id: 57, body: 'The Fear of Rejection'},
  {id: 58, body: 'The Importance of Continuing'},
  {id: 59, body: 'The Need for Self-Honesty'},
  {id: 60, body: 'Tricky Comparisons'},
  {id: 62, body: 'Truth and Honesty'},
  {id: 63, body: 'Walk in Dry Places'},
  {id: 64, body: 'Wanting Instant Gratification'},
  {id: 65, body: 'We Cannot Live with Anger'},
  {id: 67, body: 'What about My Old Friends?'},
  {id: 68, body: 'What Blocks Acceptance?'},
  {id: 69, body: 'What Is a Principle?'},
  {id: 71, body: 'What Is Insanity?'},
  {id: 72, body: 'What Is Living One Day at a Time?'},
  {id: 73, body: 'What Is Open-Mindedness?'},
  {id: 75, body: 'What Is Sincerity?'},
  {id: 76, body: 'What Is Willingness?'},
  {id: 77, body: 'What’s Needed for Staying Sober'},
  {id: 78, body: 'When and Why We Are in the Wrong'},
  {id: 79, body: 'When Have We Made a Decision?'},
  {id: 81, body: 'When Pride Gets in My Way'},
  {id: 82, body: 'When the Worst Things Become the Best'},
  {id: 83, body: 'Who Is an Alcoholic?'},
  {id: 84, body: 'Whom Can We Fix?'},
  {id: 85, body: 'Why and How We Should Practice Forgiveness'},
  {id: 86, body: 'Why Attitude Matters'},
  {id: 87, body: 'Why Did We Drink?'},
  {id: 88, body: 'Why Do I Keep Coming Back?'},
  {id: 89, body: 'Why Have a Primary Purpose?'},
  {id: 90, body: 'Why Help Is Needed'},
  {id: 91, body: 'Why Is One Drink So Bad?'},
  {id: 92, body: 'Why Keep Coming Back?'},
  {id: 93, body: 'Why Resentment Leads the Pack'},
  {id: 94, body: 'Why Should We Make Amends?'},
  {id: 95, body: 'Why Suffer to Get Well?'},
  {id: 96, body: 'Why Work the Tenth Step?'},
  {id: 97, body: 'Willingness Is the Key'},
  {id: 98, body: 'Winning the Boredom Battle'},
];
